$ProjectRoot = Split-Path -Parent $PSScriptRoot
$GodotRoot = "C:\Users\pharr\Downloads\Godot_v4.6.2-stable_mono_win64\Godot_v4.6.2-stable_mono_win64"
$GodotExe = Join-Path $GodotRoot "Godot_v4.6.2-stable_mono_win64.exe"
$GodotConsoleExe = Join-Path $GodotRoot "Godot_v4.6.2-stable_mono_win64_console.exe"
$DotnetExe = "C:\Program Files\dotnet\dotnet.exe"
$VoiceboxRoot = "C:\Program Files\Voicebox"
$VoiceboxServerExe = Join-Path $VoiceboxRoot "voicebox-server.exe"
$VoiceboxUiExe = Join-Path $VoiceboxRoot "voicebox.exe"
$VoiceboxHost = "127.0.0.1"
$VoiceboxPort = 17493
$VoiceboxProfile = "Deep Voice"
$LlamaRoot = Join-Path $ProjectRoot "third_party\llama.cpp"
$LlamaServerExe = Join-Path $LlamaRoot "bin\llama-server.exe"
$LlamaHost = "127.0.0.1"
$LlamaPort = 18080
$PhiMiniModelPath = Join-Path $ProjectRoot "third_party\models\phi-3.5-mini-instruct\phi-3.5-mini-instruct-q4.gguf"
$PhiMiniModelAlias = "phi-3.5-mini-instruct"
$LlamaGpuLayers = 999
$LlamaContextSize = 4096
