#!/usr/bin/env python3
"""Split the current 32x64 player skeleton into starter paper-doll layers.

This is a bridge from the hand-authored skeleton contract toward the real
player-v2 paper-doll pipeline. It reads the canonical 32x64 8-direction 4-row
sheet and emits layer PNGs with matching dimensions plus a small manifest.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

TOOLS_DIR = Path(__file__).resolve().parent
if str(TOOLS_DIR) not in sys.path:
    sys.path.insert(0, str(TOOLS_DIR))

from prepare_character_sheet import ImagePixels, Pixel, read_png_rgba, write_png_rgba  # noqa: E402

SOURCE = Path("assets/art/sprites/player_v2/player_model_32x64_8dir_4row.png")
OUTPUT_ROOT = Path("assets/art/sprites/player_v2")
LAYER_DIR = OUTPUT_ROOT / "layers_32x64"
PREVIEW = OUTPUT_ROOT / "player_model_32x64_layered_preview.png"
MANIFEST = OUTPUT_ROOT / "player_model_32x64_manifest.json"
WIDTH = 256
HEIGHT = 256

# Colors generated by tools/generate_player_model_32x64_8dir.gd, quantized to PNG bytes.
OUTLINE = (11, 9, 8)
SKIN = (178, 122, 84)
SKIN_D = (109, 71, 51)
HAIR = (25, 16, 11)
VISOR = (56, 198, 242)
SUIT = (224, 96, 30)
SUIT_D = (122, 43, 19)
PLATE = (76, 91, 107)
PLATE_L = (137, 155, 168)
PACK = (43, 56, 63)
BOOT = (20, 20, 22)
SOLE = (40, 38, 35)

SKIN_LIGHT = (218, 166, 123)
SKIN_LIGHT_D = (146, 96, 69)
SKIN_MEDIUM = SKIN
SKIN_MEDIUM_D = SKIN_D
SKIN_DEEP = (101, 62, 45)
SKIN_DEEP_D = (59, 38, 31)

HAIR_DARK = HAIR
HAIR_BLOND = (164, 118, 55)
HAIR_BLOND_D = (96, 64, 32)

ENGINEER = SUIT
ENGINEER_D = SUIT_D
SETTLER = (116, 78, 46)
SETTLER_D = (58, 42, 30)
SETTLER_PLATE = (154, 111, 63)

SLOTS = {
    "base": {OUTLINE, VISOR},
    "skin": {SKIN, SKIN_D},
    "hair": {HAIR},
    "outfit": {SUIT, SUIT_D, PLATE, PLATE_L, PACK, BOOT, SOLE},
}


def blank() -> ImagePixels:
    return [[(0, 0, 0, 0) for _ in range(WIDTH)] for _ in range(HEIGHT)]


def rgb(pixel: Pixel) -> tuple[int, int, int]:
    return pixel[0], pixel[1], pixel[2]


def nearest_group(color: tuple[int, int, int]) -> str:
    if color in SLOTS["skin"]:
        return "skin"
    if color in SLOTS["hair"]:
        return "hair"
    if color in SLOTS["outfit"]:
        return "outfit"
    return "base"


def make_mask(source: ImagePixels, slot: str) -> ImagePixels:
    out = blank()
    for y, row in enumerate(source):
        for x, pixel in enumerate(row):
            if pixel[3] <= 5:
                continue
            if nearest_group(rgb(pixel)) == slot:
                out[y][x] = pixel
    return out


def remap(source: ImagePixels, mapping: dict[tuple[int, int, int], tuple[int, int, int]]) -> ImagePixels:
    out = blank()
    for y, row in enumerate(source):
        for x, pixel in enumerate(row):
            if pixel[3] <= 5:
                continue
            new_rgb = mapping.get(rgb(pixel), rgb(pixel))
            out[y][x] = (*new_rgb, pixel[3])
    return out


def compose(layers: list[ImagePixels]) -> ImagePixels:
    out = blank()
    for layer in layers:
        for y, row in enumerate(layer):
            for x, pixel in enumerate(row):
                if pixel[3] > 0:
                    out[y][x] = pixel
    return out


def main() -> int:
    width, height, source = read_png_rgba(SOURCE)
    if (width, height) != (WIDTH, HEIGHT):
        print(f"ERROR: expected {WIDTH}x{HEIGHT}, got {width}x{height}", file=sys.stderr)
        return 1

    LAYER_DIR.mkdir(parents=True, exist_ok=True)
    base = make_mask(source, "base")
    skin = make_mask(source, "skin")
    hair = make_mask(source, "hair")
    outfit = make_mask(source, "outfit")

    layers = {
        "base_body_32x64": base,
        "skin_light_32x64": remap(skin, {SKIN: SKIN_LIGHT, SKIN_D: SKIN_LIGHT_D}),
        "skin_medium_32x64": remap(skin, {SKIN: SKIN_MEDIUM, SKIN_D: SKIN_MEDIUM_D}),
        "skin_deep_32x64": remap(skin, {SKIN: SKIN_DEEP, SKIN_D: SKIN_DEEP_D}),
        "hair_short_dark_32x64": remap(hair, {HAIR: HAIR_DARK}),
        "hair_short_blond_32x64": remap(hair, {HAIR: HAIR_BLOND}),
        "outfit_engineer_32x64": outfit,
        "outfit_settler_32x64": remap(outfit, {
            SUIT: SETTLER,
            SUIT_D: SETTLER_D,
            PLATE: SETTLER_D,
            PLATE_L: SETTLER_PLATE,
            PACK: SETTLER_D,
        }),
    }

    for layer_id, image in layers.items():
        write_png_rgba(LAYER_DIR / f"{layer_id}.png", WIDTH, HEIGHT, image)

    preview = compose([
        layers["base_body_32x64"],
        layers["skin_medium_32x64"],
        layers["hair_short_dark_32x64"],
        layers["outfit_engineer_32x64"],
    ])
    diff_pixels = sum(
        1
        for y in range(HEIGHT)
        for x in range(WIDTH)
        if preview[y][x] != source[y][x]
    )
    if diff_pixels != 0:
        print(f"ERROR: layered preview differs from source by {diff_pixels} pixels", file=sys.stderr)
        return 1
    write_png_rgba(PREVIEW, WIDTH, HEIGHT, preview)

    manifest = {
        "schema": "karma.player_v2.layers_32x64.v1",
        "frameWidth": 32,
        "frameHeight": 64,
        "columns": 8,
        "rows": 4,
        "directions": ["front", "front_right", "right", "back_right", "back", "back_left", "left", "front_left"],
        "animations": ["idle", "walk1", "walk2", "walk3"],
        "layerOrder": ["base", "skin", "hair", "outfit"],
        "layers": [
            {"id": "base_body_32x64", "slot": "base", "path": "layers_32x64/base_body_32x64.png", "required": True},
            {"id": "skin_light_32x64", "slot": "skin", "path": "layers_32x64/skin_light_32x64.png"},
            {"id": "skin_medium_32x64", "slot": "skin", "path": "layers_32x64/skin_medium_32x64.png", "default": True},
            {"id": "skin_deep_32x64", "slot": "skin", "path": "layers_32x64/skin_deep_32x64.png"},
            {"id": "hair_short_dark_32x64", "slot": "hair", "path": "layers_32x64/hair_short_dark_32x64.png", "default": True},
            {"id": "hair_short_blond_32x64", "slot": "hair", "path": "layers_32x64/hair_short_blond_32x64.png"},
            {"id": "outfit_engineer_32x64", "slot": "outfit", "path": "layers_32x64/outfit_engineer_32x64.png", "default": True},
            {"id": "outfit_settler_32x64", "slot": "outfit", "path": "layers_32x64/outfit_settler_32x64.png"},
        ],
        "previewStack": ["base_body_32x64", "skin_medium_32x64", "hair_short_dark_32x64", "outfit_engineer_32x64"],
        "composite": "player_model_32x64_layered_preview.png",
    }
    MANIFEST.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    print(f"wrote {MANIFEST}")
    print(f"wrote {PREVIEW}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
